config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :workouts

  resources :exercises

  namespace :api do
    namespace :v1 do
      resources :workouts, only: [:index, :create, :destroy]
      resources :data, only: [:index]
      resources :exercises, only: [:index]
    end
  end

  namespace :admin do
    resources :exercises
  end

  resources :data, only: [:index]

  get 'fitbit/:resource/:date.json' => 'fitbit_api#data_request'

end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.3.7"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "WorkIt" %></title>

    <script src="https://use.fontawesome.com/4617c23c08.js"></script>

    <%= stylesheet_link_tag 'application',
    'https://fonts.googleapis.com/css?family=Lato',
    media: 'all', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag 'application',
'https://fonts.googleapis.com/css?family=Black+Ops+One',
 media: 'all', 'data-turbolinks-track' => true %>



    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <style>{font-family: 'Lato', sans-serifs;}</style>


    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'WorkIt', root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin', admin_exercises_path %><li>
              <% end %>
              <li><%= link_to current_user.username, workouts_path %></li>
              <li><%= link_to 'Exercises', exercises_path %></li>
              <li><%= link_to 'Graphs', data_path %></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>



    <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning" role="alert">
          <%= alert %>
        </div>
      <% end %>

    <%= yield %>


    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
</html>